apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
    - name: kafka-client
      image: dongjinleekr/kafka:2.13-2.7.0
      command:
        - sh
        - -c
        - "tail -f /dev/null"
