apiVersion: v1
kind: Pod
metadata:
  name: kafkacat
  namespace: default
spec:
  containers:
    - name: kafkacat
      image: confluentinc/cp-kafkacat:latest
      command:
        - sh
        - -c
        - "tail -f /dev/null"
